# Change baseurl before deploy
# baseurl = "https://demo.stack.jimmycai.com"
# baseURL = "https://revolmusic23.github.io/revolc-blog-hugo/"
# baseURL = "https://revolc-blog-hugo.vercel.app/"
baseURL = "https://revolc.blog/"
googleAnalytics = "G-1ZCL223PE7"
languageCode = "en-us"
# title = "RevolC.Blog"
title = "Revol.C 雷歐"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "zh-tw"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

enableRobotsTXT = true

[pagination]
pagerSize = 10