# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "rss"
name = "RSS Feed"
url = "https://revolc.blog/posts/index.xml"
weight = 5

[social.params]
icon = "rss"


[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/revolc.blog"
weight = 10

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/profile.php?id=61573093185949"
weight = 20

[social.params]
icon = "brand-facebook"

[[social]]
identifier = "linktree"
name = "Linktree"
url = "https://linktr.ee/revolc.blog"

[social.params]
icon = "brand-linktree"

[[social]]
identifier = "vocus"
name = "Vocus 方格子"
url = "https://vocus.cc/user/@revolmusic"

[social.params]
icon = "layout-dashboard"
